### ISSUE TITLE
Error when trying to bring the container up

### ISSUE THREAD

**Issue by jeremiah-k** [rubenhoenle/Matrix-MQTT-Bridge#1]
Hi, I'm very interested in this project.  After creating a new user for the bot and a new room, creating a config.ini, and then using your docker-compose.yaml, I ran `sudo docker compose up` I received this error:

```
[+] Running 2/2
 ✔ Network matrix-mqtt-bridge-docker_default  Created                                                                                                                                                           0.1s 
 ✔ Container matrix-mqtt-bridge               Created                                                                                                                                                           0.2s 
Attaching to matrix-mqtt-bridge
matrix-mqtt-bridge  | Traceback (most recent call last):
matrix-mqtt-bridge  |   File "//./matrix_mqtt_bridge.py", line 102, in <module>
matrix-mqtt-bridge  |     mqtt_client.connect(mqtt_host, int(mqtt_port))
matrix-mqtt-bridge  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
matrix-mqtt-bridge  |     return self.reconnect()
matrix-mqtt-bridge  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
matrix-mqtt-bridge  |     sock.do_handshake()
matrix-mqtt-bridge  |   File "/usr/local/lib/python3.9/ssl.py", line 1310, in do_handshake
matrix-mqtt-bridge  |     self._sslobj.do_handshake()
matrix-mqtt-bridge  | ConnectionResetError: [Errno 104] Connection reset by peer
matrix-mqtt-bridge exited with code 0
```

I checked and the mqtt credentials, address, and port are correct. I can connect with mosquitto_sub using them.  Any ideas?

**Comment by rubenhoenle** [comment]
Hi, sorry you had to wait. Seems like this is because your mosquitto broker doesn't use a connection secured via TLS. I will add a new config option to disable tls via the config.ini file.

**Comment by rubenhoenle** [comment]
Should be working with the newest docker image :smile: 

Note: Make sure to update your config.ini (see: https://github.com/rubenhoenle/Matrix-MQTT-Bridge/commit/beaf088a65d79233739a64d09644a006c6ee6e1a#diff-03c62cb3e26f06d4d8277f11504a5121def68db562388cd769c2c6aaa234a811R12). Set the new tls option to false and make sure to remove the Single quotes in the Matrix config section of your config.ini file (example was wrong, there shouldn't be any quotes in the config.ini file).

**Comment by rubenhoenle** [comment]
@jeremiah-k Feel free to tell me if the fix is working for you or if there are any open issues.
